### PR TITLE
Rewrite manifest

### PR DESCRIPTION
**Pull request by ghost**
- `x-checker-data` is set up to make updating easier later (with flathubbot or GitHub Actions)
- `host-spawn` is built locally so it will work with more architectures

---

Some thoughts:

- Publish this on Flathub?
    - `flathubbot` can automatically track version changes (and merge PRs)
- Alternatively use GitHub Actions? https://github.com/marketplace/actions/flatpak-builder
- Write a new script that downloads `podman-static` in $XDG_DATA_HOME when podman isn't detected on host?

### CODE REVIEW

**Comment by ghost** [comment]
OK I forgot the credits, should I add them back?
The manifest is rewritten from the ground up though.

**Comment by ghost** [comment]
So you did local build [before](https://github.com/89luca89/io.github.luca.distrobox/blob/e8b570514b2f38de6beba345895fe5d075a21a49/io.github.luca.distrobox.yml) and later [changed](https://github.com/89luca89/io.github.luca.distrobox/commit/19edc8f4ca089001cc95f9a477491dd32b4ad8fe) to fetching compiled binary directly.

Well, this is embarrassing. Shouldn't have rewrite it in the first place. But i'll leave this PR opened for now

**Comment by 89luca89** [comment]
I'm not against this at all
I just did it because it was simpler, but it's the better approach clearly

**Comment by 89luca89** [comment]
About Flathub
2 thoughts on this:

1 - this is not nearly ready enough for prime time yet :P 
2 - they already suggested me that this won't be accepted as it runs **everything** via `host-spawn` bypassing the sandbox

**Pull request merged**
